class RuberLapide
	@@VERBA = [
		"lorem", "ipsum", "dolor", "sit", "amet",
		"a", "ac", "accumsan", "ad", "adipisicing",
		"aenean", "aliqua", "aliquam", "aliquet", "aliquip",
		"anim", "ante", "aptent", "arcu", "at",
		"auctor", "augue", "aute", "bibendum", "blandit",
		"cillum", "class", "commodo", "condimentum", "congue",
		"consectetaur", "consequat", "conubia", "convallis", "cras",
		"cubilia", "culpa", "cupidatat", "curabitur", "curae",
		"cursus", "dapibus", "deserunt", "diam", "dictum",
		"dictumst", "do", "dolore", "donec", "dui",
		"duis", "ea", "egestas", "eget", "eiusmod",
		"eleifend", "elementum", "elit", "enim", "erat",
		"eros", "esse", "est", "et", "etiam",
		"eu", "euismod", "ex", "excepteur", "exercitation",
		"facilisis", "fames", "faucibus", "felis", "fermentum",
		"feugiat", "fringilla", "fugiat", "fusce", "gravida",
		"habitant", "habitasse", "hac", "hendrerit", "himenaeos",
		"iaculis", "id", "imperdiet", "in", "inceptos",
		"incididunt", "integer", "interdum", "irure", "justo",
		"labore", "laboris", "laborum", "lacinia", "lacus",
		"laoreet", "lectus", "leo", "libero", "ligula",
		"litora", "lobortis", "luctus", "maecenas", "magna",
		"malesuada", "massa", "mattis", "mauris", "metus",
		"mi", "minim", "molestie", "mollis", "mollit",
		"morbi", "nam", "nec", "neque", "netus",
		"nibh", "nisi", "nisl", "non", "nostra",
		"nostrud", "nulla", "nullam", "nunc", "occaecat",
		"odio", "officia", "orci", "ornare", "pariatur",
		"pellentesque", "per", "pharetra", "phasellus", "placerat",
		"platea", "porta", "porttitor", "posuere", "potenti",
		"praesent", "pretium", "primis", "proident", "proin",
		"pulvinar", "purus", "quam", "qui", "quis",
		"quisque", "reprehenderit", "rhoncus", "risus", "rutrum",
		"sagittis", "sapien", "scelerisque", "sed", "sem",
		"semper", "senectus", "sint", "sociosqu", "sodales",
		"sollicitudin", "sunt", "suscipit", "suspendisse", "taciti",
		"tellus", "tempor", "tempus", "tincidunt", "torquent",
		"tortor", "tristique", "turpis", "ullamco", "ullamcorper",
		"ultrices", "ultricies", "urna", "ut", "varius",
		"vehicula", "vel", "velit", "venenatis", "veniam",
		"vestibulum", "vitae", "vivamus", "viverra", "voluptate",
		"volutpat", "vulputate", "ruber", "lapis"
	]

	public
	def self.verba() @@VERBA end
end